
 CREATE TABLE TCERTIFICATE 
   (	"C_FUNDACCO" VARCHAR2(12) NOT NULL ENABLE, 
"C_CUSTNO" VARCHAR2(12) NOT NULL ENABLE, 
"C_CUSTTYPE" CHAR(1) NOT NULL ENABLE, 
"C_IDENTITYNO" VARCHAR2(30), 
"C_IDENTITYTYPE" CHAR(1) NOT NULL ENABLE, 
"C_CUSTNAME" VARCHAR2(160), 
"C_TANO" CHAR(2), 
"C_SPECIALACCOUNT" CHAR(1) DEFAULT '0', 
 CONSTRAINT "PK_CERT_FUNDACCO" PRIMARY KEY ("C_FUNDACCO") ENABLE
   ) ORGANIZATION INDEX NOCOMPRESS PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
 PCTTHRESHOLD 50;

 
 insert into TCERTIFICATE values('a','b','c','d','e','f','g','h');
 commit;
 
 delete from TCERTIFICATE where C_FUNDACCO='a';
 insert into TCERTIFICATE values('a','b','c','d','e','f','g','h');
 commit;